### ISSUE TITLE
Update documentation to include dependency on SQLCLR

### ISSUE THREAD

**Issue by WilliamOckham** [Microsoft/GraphView#2]
This project requires CLR integration to be enabled on SQL Server and the default for that feature is disabled. The documentation should include instructions for enabling the CLR:

``` SQL
sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'clr enabled', 1;
GO
RECONFIGURE;
GO
```

**Comment by liangjeffchen** [comment]
thanks for the reminder. Have updated the doc.
