### ISSUE TITLE
Query syntax Question

### ISSUE THREAD

**Issue by chsword** [Microsoft/GraphView#8]
This query works well:

``` SQL
select x.id, y.orderId, y.fullname from mobile x,trade y match x-[hastrade]->y
```

This exception is reported:

``` SQL
select x.id, y.orderId, y.fullname from mobile x,trade y match x-hastrade->y
```

I think they should be equivalent.

**Comment by liangjeffchen** [comment]
It is by the language design that an edge is enclosed by a pair of brackets. While removing the brackets has no semantic implications, it changes syntactic parsing. So we are going to keep it this way, unless there is a strong demand on doing so. We will make error messages more informative though.
